[project]
name = "trainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "configmate[standard]>=0.1.8",
    "datasets>=4.4.1",
    "ipykernel>=7.1.0",
    "pyvene>=0.1.8",
    "sglang>=0.5.2",
    "transformers>=4.57.5",
    "vllm>=0.13.0",
]
