[project]
name = "trainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.12.0",
    "configmate[standard]>=0.1.8",
    "datasets>=4.4.1",
    "debugpy-run>=1.16",
    "flash-attn>=2.8.3",
    "flashinfer-cubin>=0.6.3",
    "flashinfer-python==0.2.7.post1",
    "gem>=0.1.12",
    "hydra-core>=1.3.2",
    "ipykernel>=7.1.0",
    "liger-kernel>=0.6.4",
    "loguru>=0.7.3",
    "nvidia-ml-py>=13.580.82",
    "nvitop>=1.6.1",
    "omegaconf>=2.3.0",
    "orjson>=3.11.5",
    "packaging>=25.0",
    "pyvene>=0.1.8",
    "ray>=2.53.0",
    "ring-flash-attn==0.1.8",
    "sgl-kernel==0.2.4",
    "sglang==0.4.9",
    "sglang-router>=0.3.2",
    "torch==2.6.*",
    "torch-memory-saver>=0.0.9",
    "torchao==0.13.0",
    "torchaudio>=2.3.1",
    "torchdata>=0.11.0",
    "torchvision>=0.18.1",
    "transformers>=4.57.5",
    "uvloop>=0.22.1",
    "vllm>=0.7.3",
    "wandb>=0.24.2",
    "wheel>=0.46.3",
]
