defaults:
- _self_
- actor: fsdp

data:
  train:
    path: null
    max_length: null
    batch_size: 32
    system_prompt: null 
    prompt_key: prompt
    chosen_key: chosen
    rejected_key: rejected
    chosen_messages_key: chosen_messages
    rejected_messages_key: rejected_messages
    apply_chat_template: true
    train_on_what: [assistant]
  test:
    path: null
    max_length: ${data.train.max_length}
    prompt_key: ${data.train.prompt_key}
    chosen_key: ${data.train.chosen_key}
    rejected_key: ${data.train.rejected_key}
    chosen_messages_key: ${data.train.chosen_messages_key}
    rejected_messages_key: ${data.train.rejected_messages_key}
    apply_chat_template: ${data.train.apply_chat_template}
    train_on_what: ${data.train.train_on_what}
  test_ratio: 0.03

actor:
  beta: 2.0
  gamma: 0.5

trainer:
  project: null
  experiment_name: null
  load_ckpt_from: null
  n_epochs: 1
  save_dir: ckpts/${trainer.experiment_name}
  save_freq: null
  use_wandb: true
